// <auto-generated />
using System;
using CSite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSite.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20220815050229_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CSite.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<long>("Account")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            ID = 20,
                            Account = 200L,
                            Name = "new car 1",
                            Notes = "Empty"
                        },
                        new
                        {
                            ID = 21,
                            Account = 201L,
                            Name = "new car 2",
                            Notes = "Empty"
                        },
                        new
                        {
                            ID = 22,
                            Account = 202L,
                            Name = "new car 3",
                            Notes = "Empty"
                        });
                });

            modelBuilder.Entity("CSite.Models.CarProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CarID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CarID");

                    b.HasIndex("ProductID");

                    b.ToTable("CarProducts");
                });

            modelBuilder.Entity("CSite.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<long>("Account")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = 500,
                            Account = 210L,
                            Name = "Customer 1",
                            Notes = "Empty",
                            Phone = "+902020"
                        },
                        new
                        {
                            ID = 501,
                            Account = 211L,
                            Name = "Customer 2",
                            Notes = "Empty",
                            Phone = "+902020"
                        },
                        new
                        {
                            ID = 502,
                            Account = 212L,
                            Name = "Customer 3",
                            Notes = "Empty",
                            Phone = "+902020"
                        });
                });

            modelBuilder.Entity("CSite.Models.Expenses", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CSite.Models.ExportProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("ExportRecieptID")
                        .HasColumnType("int");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptID")
                        .HasColumnType("int");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ExportRecieptID");

                    b.HasIndex("ProductID");

                    b.ToTable("ExportProducts");
                });

            modelBuilder.Entity("CSite.Models.ExportReciept", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CarID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Paid")
                        .HasColumnType("bigint");

                    b.Property<long>("Remaining")
                        .HasColumnType("bigint");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CarID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("UserName");

                    b.ToTable("ExportReciepts");
                });

            modelBuilder.Entity("CSite.Models.ImportProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptID")
                        .HasColumnType("int");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ReceiptID");

                    b.ToTable("ImportProducts");
                });

            modelBuilder.Entity("CSite.Models.ImportReciept", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Paid")
                        .HasColumnType("bigint");

                    b.Property<long>("Remaining")
                        .HasColumnType("bigint");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("SupplierID");

                    b.HasIndex("UserName");

                    b.ToTable("ImportReciepts");
                });

            modelBuilder.Entity("CSite.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<long>("BuyingPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("SellingPrice")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 300,
                            BuyingPrice = 10300L,
                            Name = "New Car 1",
                            Quantity = 10,
                            SellingPrice = 11660L
                        },
                        new
                        {
                            ID = 301,
                            BuyingPrice = 8400L,
                            Name = "New Car 2",
                            Quantity = 5,
                            SellingPrice = 9458L
                        },
                        new
                        {
                            ID = 302,
                            BuyingPrice = 15790L,
                            Name = "New Car 3",
                            Quantity = 8,
                            SellingPrice = 17820L
                        });
                });

            modelBuilder.Entity("CSite.Models.Supplier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<long>("Account")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            ID = 400,
                            Account = 205L,
                            Name = "Supplier 1",
                            Notes = "Empty",
                            Phone = "+902020"
                        },
                        new
                        {
                            ID = 401,
                            Account = 206L,
                            Name = "Supplier 2",
                            Notes = "Empty",
                            Phone = "+902020"
                        },
                        new
                        {
                            ID = 402,
                            Account = 207L,
                            Name = "Supplier 3",
                            Notes = "Empty",
                            Phone = "+902020"
                        });
                });

            modelBuilder.Entity("CSite.Models.Transactions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("AccountID")
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<int?>("OperationID")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CSite.Models.Users", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CarID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("UserName");

                    b.HasIndex("CarID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "Amin",
                            CarID = 20,
                            Password = "csite@123",
                            Type = 0
                        },
                        new
                        {
                            UserName = "Sara",
                            CarID = 21,
                            Password = "csite@123",
                            Type = 0
                        },
                        new
                        {
                            UserName = "Javad",
                            CarID = 22,
                            Password = "csite@123",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CSite.Models.CarProduct", b =>
                {
                    b.HasOne("CSite.Models.Car", "Car")
                        .WithMany("CarProducts")
                        .HasForeignKey("CarID");

                    b.HasOne("CSite.Models.Product", "Product")
                        .WithMany("CarProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSite.Models.ExportProduct", b =>
                {
                    b.HasOne("CSite.Models.ExportReciept", "ExportReciept")
                        .WithMany("ExportProducts")
                        .HasForeignKey("ExportRecieptID");

                    b.HasOne("CSite.Models.Product", "Product")
                        .WithMany("ExportProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportReciept");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSite.Models.ExportReciept", b =>
                {
                    b.HasOne("CSite.Models.Car", "Car")
                        .WithMany("ExportReciepts")
                        .HasForeignKey("CarID");

                    b.HasOne("CSite.Models.Customer", "Customer")
                        .WithMany("ExportReciepts")
                        .HasForeignKey("CustomerID");

                    b.HasOne("CSite.Models.Users", "User")
                        .WithMany("ExportReciepts")
                        .HasForeignKey("UserName");

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSite.Models.ImportProduct", b =>
                {
                    b.HasOne("CSite.Models.Product", "Product")
                        .WithMany("ImportProducts")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSite.Models.ImportReciept", "ImportReciept")
                        .WithMany("ImportProducts")
                        .HasForeignKey("ReceiptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportReciept");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSite.Models.ImportReciept", b =>
                {
                    b.HasOne("CSite.Models.Supplier", "Supplier")
                        .WithMany("ImportReciepts")
                        .HasForeignKey("SupplierID");

                    b.HasOne("CSite.Models.Users", "User")
                        .WithMany("ImportReciepts")
                        .HasForeignKey("UserName");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSite.Models.Users", b =>
                {
                    b.HasOne("CSite.Models.Car", "Car")
                        .WithMany("Users")
                        .HasForeignKey("CarID");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CSite.Models.Car", b =>
                {
                    b.Navigation("CarProducts");

                    b.Navigation("ExportReciepts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CSite.Models.Customer", b =>
                {
                    b.Navigation("ExportReciepts");
                });

            modelBuilder.Entity("CSite.Models.ExportReciept", b =>
                {
                    b.Navigation("ExportProducts");
                });

            modelBuilder.Entity("CSite.Models.ImportReciept", b =>
                {
                    b.Navigation("ImportProducts");
                });

            modelBuilder.Entity("CSite.Models.Product", b =>
                {
                    b.Navigation("CarProducts");

                    b.Navigation("ExportProducts");

                    b.Navigation("ImportProducts");
                });

            modelBuilder.Entity("CSite.Models.Supplier", b =>
                {
                    b.Navigation("ImportReciepts");
                });

            modelBuilder.Entity("CSite.Models.Users", b =>
                {
                    b.Navigation("ExportReciepts");

                    b.Navigation("ImportReciepts");
                });
#pragma warning restore 612, 618
        }
    }
}
